baseURL = 'https://ben.straub.cc/'
languageCode = 'en-us'
title = 'Ben Straub'
theme = 'mini'

[social]
	github = 'https://github.com/ben'
	twitter = "https://twitter.com/benstraub"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.parser]
			wrapStandAloneImageWithinParagraph = false
			[markup.goldmark.parser.attribute]
				block = true
				title = true
