baseURL = 'https://ben.straub.cc/'
languageCode = 'en-us'
title = 'Ben Straub'
theme = 'github.com/nodejh/hugo-theme-mini'

[social]
github = 'https://github.com/ben'
twitter = "https://twitter.com/benstraub"

[markup]
[markup.goldmark.renderer]
unsafe = true
