baseURL = 'https://ben.straub.cc/'
languageCode = 'en-us'
title = 'Ben Straub'
theme = 'hugo-paper'
author = 'Ben Straub'
copyright = "Copyright © {{ .Now.Year }}, Ben Straub"
enableEmoji = true

[params]
color = 'white'
github = 'https://github.com/ben'
twitter = "https://twitter.com/benstraub"
favicon = "images/favicon.ico"
appleTouchIcon = "images/avatar.png"
monoDarkIcon = true

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "talks"
name = "Talks"
url = "/talks/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true
